# Generated by Django 4.2.20 on 2025-04-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('expeditor', 'Expeditor'), ('dispatcher', 'Dispatcher'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
