# Generated by Django 4.2.20 on 2025-04-15 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.IntegerField(unique=True)),
                ('loading_date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('package_count', models.IntegerField()),
                ('total_height', models.FloatField()),
                ('total_weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('plant_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer.planttransfer')),
            ],
        ),
    ]
