# Generated by Django 4.2.20 on 2025-04-15 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='plant_transfer',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='plant',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='up',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
