# Generated by Django 4.2.20 on 2025-04-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('delivery_note', '0002_remove_deliverynote_plant_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='orders.order'),
        ),
    ]
