# Generated by Django 4.2.20 on 2025-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.CharField(max_length=11)),
                ('plant', models.CharField(max_length=11)),
            ],
        ),
    ]
