# Generated by Django 4.2.20 on 2025-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttransfer',
            name='up',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
