# Generated by Django 4.2.20 on 2025-04-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')], default=0)),
                ('up_user', models.CharField(default='151561', max_length=100)),
                ('up', models.CharField(max_length=10)),
                ('plant', models.CharField(max_length=10)),
                ('loading_date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('terms_of_delivery', models.CharField(default='FCA', max_length=100)),
                ('packages_type', models.CharField(max_length=255)),
                ('package_count', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('ldm', models.FloatField()),
            ],
        ),
    ]
